// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/27/2025, 8:12:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/plugins/**/*.{js,ts,mjs}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/composables/**/*.{js,ts,mjs}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/utils/**/*.{js,ts,mjs}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kokmi/Documents/GitHub/notesapp-tb-mk/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;